### ISSUE TITLE
Feeds can not be SSL encrypted

### ISSUE THREAD

**Issue by sangyye** [moonmoon/moonmoon#68]
I tried to add feeds that use ssl and it's not working. If i disable ssl it is working. So I think moonmoon can not read ssl feeds.

**Comment by nashe** [comment]
I just tried to add a HTTPS feed with the last version of `moonmoon` and everything works smoothly. Are you still using it? Do you still have the issue? In my opinion, the only way of not being able to load feeds over SSL/TLS would be a server presenting invalid (self-signed, expired…) certificates. 
Unfortunately, since this issue is pretty old and https://klein2.org seems to be offline, I can't confirm it.

**Comment by nashe** [comment]
I just landed https://github.com/moonmoon/moonmoon/commit/8406cec349ca59a62004efe3bc01124a609219fa, which adds an option (`checkcerts`) telling if we should check (or not) remote website's SSL certificates. By default, this option is set to `true` (certificates will be checked).
